Repository withfoodmate/frontend, pull requests merged in 2023-09, with the labels that each got.

#8 FOOMATE #6 폴더 구조 생성
  README.md
  src/api/_README.md
  src/assets/_README.md
  src/components/_README.md
  src/components/common/_README.md
  src/components/main-page/_README.md
  src/constants/_README.md
  src/hooks/_README.md
  src/mocks/_README.md
  src/pages/_README.md
  src/store/_README.md
  src/styles/_README.md
  src/types/_README.md
  src/utils/_README.md
Labels: enhancement

#5 FOOMATE #4 Recoil 상태관리 기본셋팅
  package.json
  src/main.tsx
  yarn.lock
Labels: enhancement

#9 FOODMATE main <- develop 정기병합
  README.md
  package.json
  src/api/_README.md
  src/assets/_README.md
  src/components/_README.md
  src/components/common/_README.md
  src/components/main-page/_README.md
  src/constants/_README.md
  src/hooks/_README.md
  src/main.tsx
  src/mocks/_README.md
  src/pages/_README.md
  src/store/_README.md
  src/styles/_README.md
  src/types/_README.md
  src/utils/_README.md
  yarn.lock
Labels: deploy

#18 [style] : 전역 스타일 및 테마색 추가
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  src/styles/DefaultTheme.ts
  src/styles/GlobalStyle.ts
Labels: enhancement

#28 FOOTMATE #7 식사 모임 페이지 추가
  package.json
  src/components/common/BasicButton.tsx
  src/components/common/BasicInput.tsx
  src/components/common/BasicPadding.tsx
  src/components/common/MenuLabel.tsx
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/components/findFoodmate/MenuLabels.tsx
  src/mocks/postCardData.ts
  src/pages/FindFoodmate.tsx
  src/styles/DefaultTheme.ts
  src/types/menuType.ts
  src/types/postCardType.ts
  yarn.lock
Labels: enhancement

#32 FOODMATE #29 프로필 모달 컴포넌트 생성
  src/components/common/ProfileModal.tsx
  src/components/findFoodmate/MenuLabels.tsx
  src/constants/menu.ts
  src/types/userInfoType.ts
Labels: enhancement

#37 FOODMATE #34 #36 협업을 위한 개발환경 통합
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  src/App.tsx
  src/components/common/BasicButton.tsx
  src/components/common/BasicInput.tsx
  src/components/common/BasicPadding.tsx
  src/components/common/Dropdown.tsx
  src/components/common/MenuLabel.tsx
  src/components/common/Nav.tsx
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/components/common/ProfileModal.tsx
  src/components/findFoodmate/MenuLabels.tsx
  src/constants/menu.ts
  src/index.css
  src/main.tsx
  src/mocks/postCardData.ts
  src/pages/FindFoodmate.tsx
  src/styles/DefaultTheme.ts
  src/styles/GlobalStyle.ts
  src/types/fonts.d.ts
  src/types/menuType.ts
  src/types/postCardType.ts
  src/types/userInfoType.ts
  vite.config.ts
  yarn.lock
Labels: enhancement, deploy

#40 FOODMATE #33 밥친구구해요 상세글 보기 페이지
  index.html
  src/components/common/SmallGrayButton.tsx
  src/components/createMeetingPost/Comments.tsx
  src/components/createMeetingPost/CommentsList.tsx
  src/components/createMeetingPost/RepliesList.tsx
  src/components/kakao/KakaoMap.tsx
  src/mocks/postCardData.ts
  src/pages/CreateMeetingPost.tsx
  src/styles/DefaultTheme.ts
  src/types/postCardType.ts
Labels: enhancement

#46 FOODMATE #26 로그인 페이지 추가
  package.json
  src/assets/kakao_login.png
  src/pages/Login.tsx
  yarn.lock
Labels: enhancement
