Repository withfoodmate/frontend, pull requests merged in 2023-10, with the labels that each got.

#49 FOODMATE #41 밥친구구해요 모임글 작성 페이지
  .gitignore
  .vscode/settings.json
  index.html
  package.json
  src/App.tsx
  src/components/common/BasicButton.tsx
  src/components/common/MenuLabel.tsx
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/components/common/SmallGrayButton.tsx
  src/components/createMeetingPost/Comments.tsx
  src/components/createMeetingPost/CommentsList.tsx
  src/components/createMeetingPost/RepliesList.tsx
  src/components/findFoodmate/MenuLabels.tsx
  src/components/groupPost/TinyEditor.tsx
  src/components/kakao/getGeocode.ts
  src/components/meetingPostDetailView/Comments.tsx
  src/components/meetingPostDetailView/CommentsList.tsx
  src/components/meetingPostDetailView/RepliesList.tsx
  src/constants/nav-menus.ts
  src/main.tsx
  src/mocks/postCardData.ts
  src/pages/CreateGroupPost.tsx
  src/pages/CreateMeetingPost.tsx
  src/pages/FindFoodmate.tsx
  src/pages/MeetingPostDetailView.tsx
  src/types/mapType.ts
  src/types/postCardType.ts
  yarn.lock
Labels: enhancement

#56 FOODMATE #39 랭킹 컴포넌트 개발
  src/components/common/Nav.tsx
  src/components/main-page/Ranking.tsx
  src/constants/ranking.ts
  src/mocks/rankingData.ts
  src/styles/GlobalStyle.ts
  yarn.lock
Labels: enhancement

#57 FOODMATE #31 메인페이지 검색컴포넌트 개발
  src/assets/mainbg.png
  src/assets/skeleton.gif
  src/components/main-page/Search.tsx
  src/hooks/useDebounce.ts
  src/mocks/serchData.ts
  yarn.lock
Labels: enhancement

#60 FOODMATE #54 모임 정보 - 신청 내역 페이지 생성
  src/App.tsx
  src/components/common/SideMenu.tsx
  src/components/meetingInfo/MeetingInfoCard.tsx
  src/components/meetingInfo/MeetingInfoCardList.tsx
  src/constants/menu.ts
  src/constants/nav-menus.ts
  src/pages/History.tsx
  src/pages/Inquiry.tsx
  src/styles/DefaultTheme.ts
Labels: enhancement

#63 FOODMATE #45 회원가입페이지 추가
  src/App.tsx
  src/components/register/MenuLabel.tsx
  src/components/register/food.tsx
  src/pages/Register.tsx
  src/regex/Regex.tsx
Labels: enhancement

#62 FOODMATE #16 메인페이지 Route 연결
  src/App.tsx
  src/assets/error.png
  src/assets/spinner.gif
  src/components/common/Image.tsx
  src/components/common/Nav.tsx
  src/components/main-page/Ranking.tsx
  src/components/main-page/Search.tsx
  src/components/main-page/TodayMeeting.tsx
  src/constants/ranking.ts
  src/hooks/useImage.ts
  src/mocks/rankingData.ts
  src/pages/MainPage.tsx
  src/utils/ScrollToTop.tsx
Labels: enhancement

#71 FOODMATE #65 PR 회원가입페이지 리팩토링
  src/pages/Register.tsx
  src/regex/Regex.tsx
Labels: enhancement

#72 [feat] 프록시 설정
  package.json
  src/vite-env.d.ts
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#74 FOODMATE #64 회원 가입 페이지 리팩토링
  src/components/register/MenuLabel.tsx
  src/components/register/UserProfileImage.tsx
  src/components/register/food.tsx
  src/pages/Register.tsx
Labels: enhancement

#73 FOODMATE #59 채팅창 컴포넌트 기능 구현
  .vscode/settings.json
  src/App.tsx
  src/assets/chat-foodmate-default-profile.svg
  src/assets/default-chat-user-profile.svg
  src/assets/main-background.png
  src/assets/message.svg
  src/components/chat/Home.tsx
  src/components/chat/Message.tsx
  src/components/chat/Room.tsx
  src/components/common/Image.tsx
  src/components/main-page/Ranking.tsx
  src/components/main-page/Search.tsx
  src/mocks/searchData.ts
  src/pages/Chat.tsx
Labels: enhancement

#79 FOODMATE #78 react-query 설치 및 세팅
  package.json
  src/main.tsx
  yarn.lock
Labels: enhancement

#75 FOODMATE #66 PR 개인정보변경페이지(마이페이지) 추가
  src/App.tsx
  src/components/common/LoginButton.tsx
  src/components/common/Nav.tsx
  src/components/common/SideMenu.tsx
  src/constants/mypage.ts
  src/constants/nav-menus.ts
  src/pages/Password.tsx
  src/pages/Profile.tsx
  src/pages/Quit.tsx
Labels: enhancement

#76 FOODMATE #58 Footer 컴포넌트 추가
  src/App.tsx
  src/components/common/Footer.tsx
Labels: enhancement

#80 FOODMATE #77 메인페이지 API 연동
  src/api/groupApi.ts
  src/api/rankingApi.ts
  src/components/common/Image.tsx
  src/components/common/PostCard.tsx
  src/components/main-page/Ranking.tsx
  src/components/main-page/Search.tsx
  src/components/main-page/TodayMeeting.tsx
  src/hooks/useFoodRanking.ts
  src/hooks/useLikesRanking.ts
  src/hooks/useMeetingRanking.ts
  src/hooks/useQuickSearch.ts
  src/hooks/useTodayMeeting.ts
  src/types/pagination.ts
  src/types/quickSearchType.ts
  src/types/ranking.ts
  src/types/todayMeetingType.ts
Labels: enhancement, fix

#87 FOODMATE #69 밥 친구 구해요 데이터 연동
  package-lock.json
  package.json
  src/api/groupApi.ts
  src/components/common/BasicInput.tsx
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/components/findFoodmate/DatePickerInput.tsx
  src/components/findFoodmate/DatePickers.tsx
  src/components/findFoodmate/MenuLabels.tsx
  src/components/kakao/CurrentLocation.tsx
  src/hooks/useCurrentLocation.ts
  src/pages/FindFoodmate.tsx
  src/types/postCardType.ts
  src/utils/formatDate.ts
  yarn.lock
Labels: enhancement, fix

#88 FOODMATE #83 모임 생성 기능 추가
  src/api/groupApi.ts
  src/pages/CreateGroupPost.tsx
  src/types/postCardType.ts
  src/utils/removeDot.ts
  yarn.lock
Labels: enhancement, fix

#86 FOODMATE #81 Nav 컴포넌트 반응형 추가
  src/App.tsx
  src/components/common/Drawer.tsx
  src/components/common/Nav.tsx
  src/components/main-page/Ranking.tsx
  src/store/drawer.ts
  yarn.lock
Labels: enhancement

#96 FOODMATE #93 메인페이지 반응형 스타일 추가
  package.json
  src/components/chat/Home.tsx
  src/components/chat/Message.tsx
  src/components/chat/Room.tsx
  src/components/common/Drawer.tsx
  src/components/common/Footer.tsx
  src/components/common/Nav.tsx
  src/components/main-page/Ranking.tsx
  src/components/main-page/Search.tsx
  src/components/main-page/TodayMeeting.tsx
  src/pages/Chat.tsx
  yarn.lock
Labels: enhancement

#97 FOODMATE #95 로그인 기능 구현
  src/api/memberApi.ts
  src/pages/Login.tsx
  src/store/groupAtoms.ts
Labels: enhancement, fix

#105 Feature/jihye #102 공용 fetchCall 함수 생성 및 댓글 등록 기능
  src/api/fetchCall.ts
  src/api/groupApi.ts
  src/components/meetingPostDetailView/Comments.tsx
  src/components/meetingPostDetailView/CommentsList.tsx
  src/components/meetingPostDetailView/CreateComments.tsx
  src/pages/CreateGroupPost.tsx
  src/pages/MeetingPostDetailView.tsx
  src/pages/ModifyPost.tsx
Labels: enhancement

#107 FOODMATE #106 댓글 수정/삭제
  src/api/fetchCall.ts
  src/api/memberApi.ts
  src/components/meetingPostDetailView/CommentsList.tsx
  src/components/meetingPostDetailView/CreateComments.tsx
  src/pages/Login.tsx
  src/pages/MeetingPostDetailView.tsx
  src/utils/getRefreshTokenCookie.ts
Labels: enhancement

#109 FOODMATE #108 요청 조회 페이지 데이터 연동
  src/App.tsx
  src/api/fetchCall.ts
  src/api/memberApi.ts
  src/components/common/AlertModal.tsx
  src/components/common/PrivateRoute.tsx
  src/components/meetingInfo/MeetingInfoRequestCard.tsx
  src/components/meetingInfo/MeetingInfoRequestCardList.tsx
  src/constants/nav-menus.ts
  src/pages/FindFoodmate.tsx
  src/pages/History.tsx
  src/pages/Inquiry.tsx
  src/pages/Neighborhood.tsx
  src/store/meetingInfo.ts
  src/types/postCardType.ts
  src/utils/getRefreshTokenCookie.ts
Labels: enhancement

#110 FOODMATE #47 PR 로그인 페이지 비밀번호 찾기 모달창 UI 추가
  src/assets/kakao_login_large.png
  src/components/login/passwordModal.tsx
  src/pages/Login.tsx
  src/pages/Password.tsx
  src/pages/Quit.tsx
Labels: enhancement

#114 FOODMATE #113 좋아요 기능 추가
  src/api/memberApi.ts
  src/components/common/PostCard.tsx
  src/components/common/ProfileModal.tsx
  src/components/meetingPostDetailView/CommentsList.tsx
  src/pages/MeetingPostDetailView.tsx
  src/store/login.ts
  src/types/userInfoType.ts
Labels: enhancement

#116 FOODMATE #84 채팅 API 연동
  .vscode/settings.json
  package-lock.json
  package.json
  src/api/ChatApi.ts
  src/api/rankingApi.ts
  src/assets/chatroom-skeleton.webp
  src/assets/message-skeleton_full.gif
  src/assets/message-skeleton_half.gif
  src/components/chat/Home.tsx
  src/components/chat/MemberThumbnail.tsx
  src/components/chat/Message.tsx
  src/components/chat/Room.tsx
  src/components/common/Image.tsx
  src/components/common/Nav.tsx
  src/components/main-page/Search.tsx
  src/constants/chatNavType.ts
  src/hooks/useChatroomList.ts
  src/hooks/useChatroomMessage.ts
  src/hooks/useMeetingRanking.ts
  src/pages/Chat.tsx
  src/types/chatroomMessageType.ts
  src/types/chatroomType.ts
  src/vite-env.d.ts
  yarn.lock
Labels: enhancement

#118 FOODMATE #115 신청 내역 페이지 데이터 연동
  src/components/common/PostCard.tsx
  src/components/meetingInfo/MeetingInfoCard.tsx
  src/components/meetingInfo/MeetingInfoCardList.tsx
  src/components/meetingInfo/MeetingInfoRequestCard.tsx
  src/pages/FindFoodmate.tsx
  src/pages/History.tsx
  src/pages/Inquiry.tsx
  src/pages/MeetingPostDetailView.tsx
  src/pages/Neighborhood.tsx
  src/store/meetingInfo.ts
  src/types/postCardType.ts
  src/utils/formatDate.ts
Labels: enhancement

#121 FOODMATE #120 모임 참여 기능 추가
  src/pages/MeetingPostDetailView.tsx
Labels: enhancement

#123 FOODMATE #85 Nav API 연동
  src/api/ChatApi.ts
  src/api/memberApi.ts
  src/components/chat/Home.tsx
  src/components/chat/MemberThumbnail.tsx
  src/components/chat/Message.tsx
  src/components/common/Nav.tsx
  src/constants/auth.ts
  src/hooks/useChatroomMessage.ts
  src/hooks/useMyProfile.ts
  src/pages/Chat.tsx
  src/pages/MeetingPostDetailView.tsx
Labels: enhancement

#124 FOODMATE #122 회원 가입 페이지 리팩토링
  src/api/memberApi.ts
  src/constants/mypage.ts
  src/pages/Register.tsx
  src/types/registerType.ts
Labels: enhancement, fix

#128 FOODMATE #126 채팅 참여 기능 재추가
  src/components/common/Nav.tsx
  src/pages/MeetingPostDetailView.tsx
Labels: fix

#131 FOODMATE #130 밥친구구해요 검색 데이터 버그 수정
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/pages/FindFoodmate.tsx
Labels: bug

#132 FOODMATE main <- develop 정기병합
  src/components/common/PostCard.tsx
  src/components/common/PostCardsList.tsx
  src/pages/FindFoodmate.tsx
Labels: deploy

#134 FOODMATE #133 파비콘 추가 및 경로수정
  index.html
  src/components/common/Nav.tsx
Labels: documentation

#136 FOODMATE #135 : 모임 참여 기능 삭제된 코드 복구
  src/components/meetingInfo/MeetingInfoCard.tsx
  src/pages/CreateGroupPost.tsx
  src/pages/MeetingPostDetailView.tsx
Labels: fix

#139 Feature/mijin #138
  src/components/common/BasicPadding.tsx
  src/components/common/LoginButton.tsx
  src/components/common/SideMenu.tsx
  src/components/mypage/food.tsx
  src/components/register/food.tsx
  src/pages/Password.tsx
  src/pages/Profile.tsx
  src/pages/Quit.tsx
  src/pages/Register.tsx
Labels: enhancement

#140 FOODMATE #137 전체적인 코드 리팩토링
  src/api/memberApi.ts
  src/components/common/PostCardsList.tsx
  src/pages/Inquiry.tsx
  src/pages/Neighborhood.tsx
  src/pages/Password.tsx
  src/pages/Profile.tsx
  src/pages/Quit.tsx
  src/utils/getRefreshTokenCookie.ts
Labels: bug
